spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        # url: jdbc:oracle:thin:@192.168.0.37:1521:orcl
        # username: student
        # password: 1234
        url: jdbc:oracle:thin:@192.168.0.137:1521:xe
        username: accountbook
        password: ab1234

    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.Oracle12cDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true 

server:
    port: 9091
    
logging:
    level:
        root: INFO



##

accountbook:
    app:
        name: ACCOUNT_BOOK
        
    jwt:
        secretKey: book!@sec
        tokenValidTime: 6000000
        tokenType: accbook
        refreshKey: book!@sec
        refreshValidTime: 18000000
