
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.0.37:1521:orcl
        username: student
        password: 1234

    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.Oracle12cDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true 

server:
    port: 9090
    
logging:
    level:
        root: INFO